/*
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <iostream>

using namespace std;

int main()
{
  int fibo_now = 1;
  int fibo_last = 1;

  int sum = 0;
  while (fibo_now <= 4000000)
    {
      cout << fibo_now << endl;
      if (fibo_now % 2 == 0)
        {
          sum += fibo_now;
        }
      int temp = fibo_now;
      fibo_now = fibo_now + fibo_last;
      fibo_last = temp;
    }

  cout << "SUM: " << sum;
}
